version: "3"

services:
  php:
    build:
      context: .
      dockerfile: dev/docker/Dockerfile
    ports:
      - 8086:80
    volumes:
      - $PWD/..:/app
    environment:
      - APACHE_DOCUMENT_ROOT=/app/example-singlepass/html